language: minimal

services:
  - docker

jobs:
  include:
    - name: "Test"
      script:
        - docker build -t catpage --build-arg DEV=true .
        - docker run --user 0 --rm -t catpage pytest --cov=app --cov-report=term --cov-fail-under=100
